### ISSUE TITLE
 Replace Toast with Snackbar

### ISSUE THREAD

**Issue by raffranco** [raffranco/Community#5]
Better for Espresso

**Comment by raffranco** [comment]
Replace every `Toast.makeText(getApplicationContext(), "text to view", Toast.LENGTH_SHORT).show();` with Snackbar.make(AView, "text to view", Snackbar.LENGTH_LONG).show();

**Comment by GerardoAmb** [comment]
Ok @raffranco.

**Comment by raffranco** [comment]
The view to find a parent from
[https://developer.android.com/reference/android/support/design/widget/Snackbar](url)
